### PR TITLE
Add --auth-credentials option

### PR DESCRIPTION
**Pull request by knesenko**
- this option allows to pass marathon credentials
via docker params
- updated README.md

### CODE REVIEW

**Comment by brndnmtthws** [comment]
Thanks for the doc updates. You can also specify the auth params as part of the URL. Are we sure we need an additional command line flag?

**Comment by knesenko** [comment]
@brndnmtthws Correct, this could be done via the url. But I thought it will be nice to have that option as well.

**Comment by brndnmtthws** [comment]
I'm not opposed to it, but I'd to collect some feedback.

**Comment by knesenko** [comment]
Ok thanks !

**Comment by lloesche** [comment]
@brndnmtthws 
What if we call it `--auth-credentials` and drop the marathon from that string? For DC/OS 1.8 we will require marathon-lb to authenticate against Bouncer and hand an auth token to Marathon. That way we could then reuse the same arg to provide login:pass data and just introduce an extra arg that tells marathon-lb to acquire an auth token before speaking to Marathon.

**Comment by brndnmtthws** [comment]
That makes sense. Sounds reasonable to me.

**Comment by knesenko** [comment]
@lloesche @brndnmtthws want me to rename the the option to` --auth-credentials` ?

**Comment by brndnmtthws** [comment]
Thanks!

**Comment by luhkevin** [comment]
Is this working? I'm running marathon-lb with `--auth-credentials` flag set equal to my username and password, and I'm getting this error:

```
marathon_lb: SSE Active, trying fetch events from http://master.mesos:8080/v2/events
marathon_lb: fetching apps
marathon_lb: GET http://master.mesos:8080/v2/apps?embed=apps.tasks
marathon_lb: Unexpected error!
Traceback (most recent call last):
  File "/marathon-lb/marathon_lb.py", line 1172, in do_reset
    self.__apps = get_apps(self.__marathon)
  File "/marathon-lb/marathon_lb.py", line 951, in get_apps
    apps = marathon.list()
  File "/marathon-lb/marathon_lb.py", line 201, in list
    params={'embed': 'apps.tasks'})["apps"]
  File "/marathon-lb/marathon_lb.py", line 188, in api_req
    return self.api_req_raw(method, path, self.__auth, **kwargs).json()
  File "/marathon-lb/marathon_lb.py", line 180, in api_req_raw
    if 'message' in response.json():
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 812, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
marathon_lb: fetching apps
```

I also have the marathon URI set equal to `http://username:password@master.mesos:8080`. 

Is there another place I have to set the username/password? Why is marathon-lb not authenticating when it's trying to fetch events?

**Comment by luhkevin** [comment]
Oh, nvm. This turned out to be an old log. It's indeed prepending the credentials in the request.

**Pull request merged**
