### PR TITLE
Bump HAProxy from 1.8.4 to 1.8.8

### PR DESCRIPTION
**Pull request by justinrlee**

### CODE REVIEW

**Comment by vespian** [comment]
@justinrlee Do you think you could check if the CI failure is related?

**Comment by GoelDeepak** [comment]
LGTM!

**Comment by justinrlee** [comment]
@vespian Pretty sure CI is not related, but I'll check again tomorrow or Monday.

**Comment by jkoelker** [comment]
Closing in favor or #608

**Pull request closed without merging**
