### PR TITLE
HTTP basic auth support

### PR DESCRIPTION
**Pull request by vixns**
### Usage   

generate password hash : `openssl passwd -1 badpassword`
add an extra label : `HAPROXY_0_AUTH=My auth realm:username:$1$Xy3nnCCX$l16GhJiqDZQnBaWPYtB6K.`

Currently implemented for http and https, with path support

#### add a second username / password pair
overwrite `USERLIST_HEAD` with an extra label
```
HAPROXY_0_USERLIST_HEAD="userlist user_{backend}\n user {user} password {passwd}\n  user user2 password $1$my_hashed_password2 "
```

#### use insecure password
**Not recommanded, use with care AND protect the `_haproxy_getconfig` endpoint**
overwrite `USERLIST_HEAD` with an extra label
```
HAPROXY_0_USERLIST_HEAD="userlist user_{backend}\n user {user} insecure-password {passwd}"
HAPROXY_0_AUTH=My insecure auth realm:username:badpassword
```
#### adding an extra superadmin global username/pass 
 overwrite `USERLIST_HEAD` global template
```
userlist user_{backend}
   user superadmin password $1$my_hashed_super_password
   user {user} password {passwd}
```

### CODE REVIEW

**Comment by brndnmtthws** [comment]
Geez, we're accumulating a lot of templates like `HAPROXY_HTTPS_FRONTEND_ROUTING_ONLY_WITH_PATH_AND_AUTH`.

Anyway, PR looks good but I'll need some time to review it.

**Comment by brndnmtthws** [comment]
Can you add your notes from the PR to the Wiki? And then link to it from the README/help.

**Comment by brndnmtthws** [comment]
PR looks great, thanks for this. Just need to update the wiki with instructions, and we should be good to go.

**Comment by vixns** [comment]
Did not see any help section / links to the wiki in the README, not sure where to add this.
I'll update the wiki right after this PR's merge.

**Comment by brndnmtthws** [comment]
I created the wiki page:

https://github.com/mesosphere/marathon-lb/wiki/HTTP-Basic-Auth

I'd like to build up more examples in the wiki, and try to declutter/reorganize the README.

Anyway, I'll merge this for now. Thanks!

**Pull request merged**
