### PR TITLE
HAProxy 1.7.6

### PR DESCRIPTION
**Pull request by JayH5**

### CODE REVIEW

**Comment by robsonpeixoto** [comment]
Are you using in production, @JayH5 ?

**Comment by JayH5** [comment]
@robsonpeixoto these changes specifically, no. marathon-lb in general, yes.

**Comment by norrs** [comment]
@JayH5 : This is now fixed in https://github.com/mesosphere/marathon-lb/commit/0d850c267beb47a56d94a188d14c1c928045204d . 

I guess creating a new PR for TINI_VERSION bumping or merge this and change title to bumping TINI_VERSION.

Tho sad to see they haven't merged this earlier.

**Comment by JayH5** [comment]
@norrs It's a shame they didn't do 1.7.7. After the response to this PR (and the long list of PRs from others) I'm not in a rush to make another.

**Pull request closed without merging**
