### PR TITLE
fix bug introduced in HAPROXY_DEFAULT_GLOBAL_OPTIONS PR

### PR DESCRIPTION
**Pull request by matt-deboer**
A method rename was incomplete in the HAPROXY_DEFAULT_GLOBAL_OPTIONS pr that introduced a bug; this is the fix.

### CODE REVIEW

**Comment by moertel** [comment]
Just want to add: Newest Docker image is also broken, so whoever pulls `latest` will see this error:
```
AttributeError: 'ConfigTemplater' object has no attribute 'additional_default_options'
```
For a temporary workaround, pull `mesosphere/marathon-lb:v1.4.2` instead.

**Comment by brndnmtthws** [comment]
test this please

**Comment by brndnmtthws** [comment]
It looks like the tests are broken.

**Comment by brndnmtthws** [comment]
test this please

**Comment by matt-deboer** [comment]
hmm...not sure at this point.
All of the following pass locally:
docker run --rm -it -v $(pwd):/src python:2.7 bash -c 'cd /src && pip
install -r requirements.txt -r requirements-dev.txt && pytest --pep8 --cov'
docker run --rm -it -v $(pwd):/src python:3.4 bash -c 'cd /src && pip
install -r requirements.txt -r requirements-dev.txt && pytest --pep8 --cov'
docker run --rm -it -v $(pwd):/src python:3.5 bash -c 'cd /src && pip
install -r requirements.txt -r requirements-dev.txt && pytest --pep8 --cov'

Any ideas?

**Comment by brndnmtthws** [comment]
Try running `nosetests` instead.

**Comment by matt-deboer** [comment]
ah, it was environment variables persisting across tests; should be fixed now

**Comment by brndnmtthws** [comment]
test this please

**Pull request merged**
