### PR TITLE
fix python 2 support

### LINKED ISSUE #54: 'Module_six_moves_urllib' object has no attribute 'urlparse'
Looks like it can't start anymore:

```
Traceback (most recent call last):
  File "marathon_lb.py", line 1181, in <module>
    not args.dont_bind_http_https, args.ssl_certs)
  File "marathon_lb.py", line 1095, in run_server
    listen_uri = urllib.urlparse(listen_addr)
AttributeError: 'Module_six_moves_urllib' object has no attribute 'urlparse'
```

### PR DESCRIPTION
**Pull request by felixb**
this fixes #54, at least it works for me when running marathon-lb with python2

### CODE REVIEW

**Comment by brndnmtthws** [comment]
Looks like it's still broken. Also, you could add `2.7` in `.travis.yml` to test it automatically.

**Comment by felixb** [comment]
Finally, all tests are passing.

**Comment by brndnmtthws** [comment]
Great, thanks!

**Comment by scalp42** [comment]
I was using python3 @felixb

**Comment by felixb** [comment]
@scalp42 this PR should make it run on both versions again.

**Comment by scalp42** [comment]
it doesn't @felixb unfortunately, I'll reopen an issue.

**Pull request merged**
