### PR TITLE
Fix HTTPS path routing where only 1 vhost exists.

### PR DESCRIPTION
**Pull request by brndnmtthws**
To address #99.

### CODE REVIEW

**Comment by rvalkenaers** [comment]
I tested this with following config:

```
HAPROXY_1_VHOST = app.example.com
HAPROXY_1_PATH = /app1
```

But I'm getting on error on the validation of the haproxy.cfg:

`[ALERT] 066/133854 (21) : parsing [/tmp/tmp08iije8k:59] : error detected while parsing switching rule : no such ACL : 'path_app1_10016'.`


The config generated in /tmp dir looks like this:
```
frontend marathon_http_in
  bind *:80
  mode http
  acl host_app_example_com hdr(host) -i app.example.com
  acl path_app1_10016 path_beg /app1
  use_backend app1_10016 if host_app_example_com path_app1_10016

frontend marathon_https_in
  bind *:443 ssl crt /etc/ssl/example.com.pem
  mode http
  use_backend app1_10016 if { ssl_fc_sni app.example.com } path_app1_10016
```

I think the following line needs to be added to the https frontend:
`acl path_app1_10016 path_beg /app1`

so the config looks like this:

```
frontend marathon_https_in
  bind *:443 ssl crt /etc/ssl/example.com.pem
  mode http
  acl path_app1_10016 path_beg /app1
  use_backend app1_10016 if { ssl_fc_sni app.example.com } path_app1_10016
```

**Comment by brndnmtthws** [comment]
Yes, you're right. The ACL is missing. Thanks! I'll update the PR in a moment.

**Comment by brndnmtthws** [comment]
Give it a shot now.

**Comment by rvalkenaers** [comment]
Seems to be working now.

Thanks!

**Pull request merged**
