### PR TITLE
Remove extra slash added to request when using backend proxypass (#284)

### LINKED ISSUE #284: Double slashes in request line when using HAPROXY_0_HTTP_BACKEND_PROXYPASS
Using `HAPROXY_0_HTTP_BACKEND_PROXYPASS` adds an extra `/` to the request line.

Setup to reproduce:
* marathon-lb v1.3.2, group = internal
* Default nginx docker image named "testapp" in marathon

Labels for `testapp`:
```
HAPROXY_GROUP=internal
HAPROXY_0_VHOST=internal.example.com
HAPROXY_0_PATH=/testapp
HAPROXY_0_HTTP_BACKEND_PROXYPASS_PATH=/testapp
```
I expected the requests to end up like this:

```
http://internal.example.com/testapp     -> GET /
http://internal.example.com/testapp/    -> GET /
http://internal.example.com/testapp/foo -> GET /foo
```

But in the logs this is what I see:

```
[04/Aug/2016:08:15:17 +0000] "GET / HTTP/1.1" 200 
[04/Aug/2016:08:15:18 +0000] "GET // HTTP/1.1" 200 
[04/Aug/2016:08:15:20 +0000] "GET //foo HTTP/1.1" 404 
```

Looking through the code this is consistent with how this is implemented:
```
reqirep  "^([^ :]*)\ {proxypath}(.*)" "\\1\ /\\2"
```

This could be fixed by adding a optional `/`like so:
```
reqirep  "^([^ :]*)\ {proxypath}/?(.*)" "\\1\ /\\2"
```

### PR DESCRIPTION
**Pull request by bakstad**
This PR aims to fix #284.

### CODE REVIEW

**Comment by ssk2** [comment]
@mesosphere-ci: retest me please

**Comment by ssk2** [comment]
retest this please

**Comment by bakstad** [comment]
Hi,

I'm not sure why the "Velocity" check is failing, but the test seem to fail due to:
```
[python3.5] $ /bin/bash C:\Users\SSHD\AppData\Local\Temp\hudson4413103117014111095.sh
The system cannot find the file specified
FATAL: command execution failed
java.io.IOException: Cannot run program "/bin/bash" (in directory "C:\Windows\workspace\public-marathon-lb-pulls\python_version\python3.5"): CreateProcess error=2, The system cannot find the file specified
```
The same goes for the python2.7 build.

See https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/public-marathon-lb-pulls/179/python_version=python3.5/console

Is there anything I have forgotten to do or should have don't differently? The tests I updated seems to run fine on TravisCI.

**Comment by titosand** [comment]
retest this please

**Comment by titosand** [comment]
retest this please

**Comment by brndnmtthws** [comment]
retest this please

**Pull request merged**
