### PR TITLE
Correctly validate global daemon flag

### LINKED ISSUE #613: Imprecise config checking prevents certain HAproxy configurations
[This line](https://github.com/mesosphere/marathon-lb/blob/master/marathon_lb.py#L459) is not a valid way to check if the ``daemon`` directive is being used.

I have a stanza I want to use in my HAproxy config:

```
  log /dev/log daemon notice
```

The ``daemon`` here is a syslog facility.

Because the config validation isn't very precise, it blocks me from starting MLB with such a configuration.

### PR DESCRIPTION
**Pull request by paambaati**
This should fix #613, reported by @jcmcken.

CC: @timcharper @brndnmtthws @drewkerrigan @justinrlee

### CODE REVIEW

**Comment by timcharper** [comment]
@paambaati that does seem better. It's been a while since I've looked at this code; should we ideally arg-parse?

**Comment by paambaati** [comment]
> should we ideally arg-parse?

@timcharper Yep.

**Comment by timcharper** [comment]
I'll merge it right now; this seems like it at least makes it better. Thank you!

**Comment by paambaati** [comment]
@timcharper While I have your attention, would you mind me asking a few questions?

1. Can you also merge #582? It is a simple enough fix.
2. What is the status of upgrades to HAProxy 1.9? I can confirm it works (we run it already on production on a medium-size cluster), but it would be nice to keep marathon-lb up to date.
3. There's been quite a few issues that aren't answered, and PRs that haven't been merged? What's the overall vision for the project looking like? Is there something contributors can help with?

**Comment by mattj-io** [comment]
Hi @paambaati - hopefully you've seen #582 has also been merged, and we've bumped HAProxy to 1.8. Apologies that this repo hasn't had much love recently, but we're actively working to improve things and merge PR's that have been received - we would definitely love to have more external contributors !

**Pull request merged**
