### PR TITLE
domain2backend use_backend ordering #342

### PR DESCRIPTION
**Pull request by SlevinBE**
fix for #342 

Contains a unit test to verify the scenario.

This fix sets the backend_weight of the app to -1 when its template uses a domain2backend map. By doing this it gets appended to the end of the section, instead of getting thrown in somewhere in the middle (which caused the unreachable service problems).

### CODE REVIEW

**Comment by brndnmtthws** [comment]
test this please

**Comment by SlevinBE** [comment]
That's strange, they are working locally (see output below). Is there an additional test set running when building in jenkins?

```
> pytest --pep8
======================================================================================= test session starts =======================================================================================
platform darwin -- Python 2.7.10, pytest-3.0.3, py-1.4.31, pluggy-0.4.0
rootdir: /Users/xxxxxx/marathon-lb, inifile:
plugins: pep8-1.0.6, cov-2.4.0
collected 82 items

bluegreen_deploy.py .
common.py .
config.py .
lrucache.py .
marathon_lb.py .
utils.py .
zdd.py .
zdd_exceptions.py .
tests/__init__.py .
tests/test_common.py ...
tests/test_marathon_lb.py .........................................
tests/test_utils.py ...............
tests/test_zdd.py ..............

==================================================================================== 82 passed in 1.00 seconds ====================================================================================
```

**Comment by brndnmtthws** [comment]
Try running:

```console
$ nosetests --nocapture
```

**Comment by brndnmtthws** [comment]
test this please

**Comment by SlevinBE** [comment]
I think I found the issue, my branch didn't have the latest master changes from this upstream repo. I've integrated these changes and the tests should now work.

**Pull request merged**
