### PR TITLE
[WIP] Introduce support for blue/green deploys.

### PR DESCRIPTION
**Pull request by brndnmtthws**
With this PR, we can execute zero downtime deployments with Marathon as described here: https://github.com/mesosphere/marathon-lb/tree/blue-green-deployment#zero-downtime-deployments

### CODE REVIEW

**Comment by brndnmtthws** [comment]
I ran a test based on [tests/run-benchmark.rb](tests/run-benchmark.rb) to validate the correctness of the code. The test involved deploying continuously for ~70 hours, and the results are here: https://docs.google.com/spreadsheets/d/1n7qa6j6wGyEA4LN2gHoGKExOLVTDGiAnJkEZ3FV5BuQ/edit?usp=sharing

**Comment by SEJeff** [comment]
@brndnmtthws What exactly is `fail_on_length`? Most of the other fields are quite obvious.

**Comment by brndnmtthws** [comment]
@SEJeff I think it means the connection was closed before all the data was received, but I'm not sure. The docs are here: https://httpd.apache.org/docs/2.2/programs/ab.html

**Comment by SEJeff** [comment]
This looks really good, but I do wish [marathon supported it natively](https://github.com/mesosphere/marathon/issues/712#issuecomment-119807562), making it easier for an app like this. I'll likely use this when it is merged however so thanks for working on it

**Pull request merged**
