### PR TITLE
use qdisc instead of iptables to prevent hanging

### PR DESCRIPTION
**Pull request by xiaods**
because iptables is block the sync packet, it caused 1s delayed.
use qdisc to prevent the hanging up.

### CODE REVIEW

**Comment by brndnmtthws** [comment]
This is missing a few pieces. You need to set up the queues, and mark SYN packets so they actually get routed to the queues. In order to do it properly, the setup should be idempotent as well.

**Comment by xiaods** [comment]
@brndnmtthws could u do me a favor, give some demo script?

**Comment by xiaods** [comment]
@brndnmtthws thanks for your reminder, i will have a try with http://engineeringblog.yelp.com/2015/04/true-zero-downtime-haproxy-reloads.html script.

**Comment by brndnmtthws** [comment]
Feel free to reopen this PR (or create another) if you feel it's ready for another review.

**Pull request closed without merging**
