### PR TITLE
Allow to specify --group and --marathon value via ENV

### PR DESCRIPTION
**Pull request by lloesche**
This implements #197 

Should be fully backwards compatible.

### CODE REVIEW

**Comment by brndnmtthws** [comment]
Looks good. Have you tested it?

**Comment by lloesche** [comment]
I tested that when started with `HAPROXY_GROUP=myapplb` `HAPROXY_MARATHON=https://leader.mesos:8443` it results in

```
   15 ?        S+     0:00 python3 /marathon-lb/marathon_lb.py --syslog-socket /dev/null --haproxy-config /marathon-lb/haproxy.cfg --ssl-certs /etc/ssl/cert.pem --command sv reload /marathon-lb/service/haproxy --sse --marathon https://leader.mesos:8443 --group myapplb --health-check
```

and when started without any extra args it runs with the same defaults it's currently using.

**Comment by brndnmtthws** [comment]
Cool, thanks!

**Comment by brndnmtthws** [comment]
This doesn't seem to work. I'm getting the following error:

```
/marathon-lb/run: line 116: MARATHON_ARGS[@]: unbound variable
```

**Comment by lloesche** [comment]
I'm looking into it. Did you provide any special arguments?

**Pull request merged**
