### PR TITLE
Add --skip-reload to not reload Haproxy on changes

### PR DESCRIPTION
**Pull request by scalp42**
cc @discordianfish

### CODE REVIEW

**Comment by discordianfish** [comment]
@scalp42 What's the use case here? Can you explain why you need this option?

**Comment by scalp42** [comment]
One of the use case is deploying an app through Marathon but not wanting to have the loadbalancing layer to immediately pick up the change (say you want to test an app on the slave locally but don't want Haproxy to pick it up).

**Comment by brndnmtthws** [comment]
Not sure I see the point, to be honest. I'm not completely opposed to it, however.

Also, can you separate the style changes out into a separate PR?

**Comment by scalp42** [comment]
@brndnmtthws should be good now :smile:

**Comment by brndnmtthws** [comment]
LGTM. Any comments @discordianfish?

**Comment by brndnmtthws** [comment]
Is this still something you need? I'm going to close the PR for now, but feel free to reopen if you want to discuss.

**Comment by scalp42** [comment]
@brndnmtthws unfortunately I still need it as it allows to "dump/debug" by launching the service twice and passing another location for `haproxy.cfg` but *making sure* it does not actually try to start/reload Haproxy.

**Comment by scalp42** [comment]
I can rebase my changes in case!

**Pull request closed without merging**
