### PR TITLE
Multiple SSL certificate config for frontend marathon_https_in

### PR DESCRIPTION
**Pull request by aladagemre**
We can now provide multiple ssl certificates for the **frontend marathon_https_in** group.

    export HAPROXY_SSL_CERTS=/etc/ssl/mesosphere.com.pem,/etc/ssl/mesosphere2.com.pem  

and then running the script will create a line like following:

    bind *:443 ssl crt /etc/ssl/mesosphere.com.pem crt /etc/ssl/mesosphere2.com.pem

We can provide single certificate:

    export HAPROXY_SSL_CERTS=/etc/ssl/mesosphere.com.pem

resulting in:

    bind *:443 ssl crt /etc/ssl/mesosphere.com.pem

Or without any env variable, it is set by default:

    bind *:443 ssl crt /etc/ssl/mesosphere.com.pem

### CODE REVIEW

**Comment by brndnmtthws** [comment]
Looks great to me. Thoughts @discordianfish?

**Comment by brndnmtthws** [comment]
Can you rebase your PR against master?

**Comment by brndnmtthws** [comment]
Could you add this as as a command line flag instead of an environment variable?

**Comment by aladagemre** [comment]
Ok I'm working on it.

**Comment by aladagemre** [comment]
Closing in favor of pull request #23

**Pull request closed without merging**
