### PR TITLE
Match logic for deriving haproxy svname from task in zdd.py

### PR DESCRIPTION
**Pull request by JamesAwesome**
This will derive a marathon task's unique backend/svname according to the same logic as the marathon_lb.py script via `utils.get_task_ip_and_ports` method: https://github.com/mesosphere/marathon-lb/blob/master/utils.py#L154 

I've also gone ahead and cleaned up some unused imports in zdd.py...

This should address Issue #209

### CODE REVIEW

**Comment by JamesAwesome** [comment]
@h0tbird if you could test that'd be cool. Despite not using the mesos agent ip in this svname as you described, the svname we now derive should be done so using the same logic as marathon_lb.py when choosing the svname for use in haproxy. So long as the two svnames match that's all that should matter.

**Comment by h0tbird** [comment]
Thank you for such a fast response, this is my current situation:

`marathon-lb.py` produces `worker-2_cell-1_dub_xnood_com_10_0_0_124_31195` (Agent IP)
`zdd.py` produces `worker-2_cell-1_dub_xnood_com_10_128_4_98_31195` (container IP)

If the same logic is used in both then I wonder if this is a matter of having enough context at  execution time. Any idea?

**Comment by JamesAwesome** [comment]
Not sure. Assuming in #209 the task json you copied into the comments produced the name `worker-2_cell-1_dub_xnood_com_10_0_0_124_31195` I'm not even sure where the `10_0_0_124` would be coming from. May be a question for somebody else on the project.

**Comment by brndnmtthws** [comment]
Thanks!

**Pull request merged**
